### ISSUE TITLE
Adsense won't load with turbolinks

### ISSUE THREAD

**Issue by chengguangnan** [turbolinks/turbolinks-classic#151]
Google adsense won't appear if you get to the page through a turbolink. 

I have no idea but perhaps it's due to the dom onload event?

JFYI.

**Comment by tomasgregor** [comment]
leods92 - thank you for the fix. To keep code structure clean I placed your code to a file required by application.js which is set download asynchronously and it works as well. Is there any reason to put the code in <head> or <body>?

**Comment by leods92** [comment]
@tomasgregor Sorry for the delay in answering. Could you elaborate? I don't understand your question.

**Comment by tomasgregor** [comment]
@leods92  I meant you placed your script in the <body> tag and elaborated on placing it in the <head> as another option. In my Rails project I put the code in a separate file turoblinks-settings.js which is required by application.js. My question was whether there's a reason to put the script directly in the body or head tag or it can be uploaded with javascript_inlcude_tag.
