### ISSUE TITLE
3rd party js libraries which need to run on every page.

### ISSUE THREAD

**Issue by willfults** [turbolinks/turbolinks-classic#166]
I'm trying to display a js chat widget on my site from http://www.olark.com

I'm trying to use the turbolinks... document.addEventListener('page:change', function() {
function so that every time a user hits a new page, the code gets executed and displays the chat window.  But it only displays after the first page load.  After that, it doesn't work.  I'm also experiencing a similar issue with a facebook recommend widget.  To duplicate simply copy and paste this code into the bottom of your html page (using a partial so it displays on every page).  Then navigate around your app, it only loads after the first page.  Is this an issue with the olark plugin or am I doing something wrong?  

Here is the code I am using - http://pastebin.com/KS6GNyNj

I am using gem version 1.0.0, Rails 3.2.11

I noticed that document.addEventListener('page:change', function() { 
Gets executed twice on the second page load.  Try something like
document.addEventListener('page:change', function() {
alert('hi')
});

Then when you hit the third page it runs 3 times, 4th page 4 times etc.

**Comment by mitosch** [comment]
Hi there

I saw this thread after trying to implement UserReport with turbolinks. Currently it is not possible to use it together.

So I thought about a generic solution:

- Create an iframe within your turbolinks app pointing to a special layout without turbolinks
- Put every third party application which doesn't support turbolinks or manual re-initialization into that iframe 
- Everytime a turbolinks page load is triggered (i guess it is "page:load" or "page:change"?) send a real page-reload to the iframe

What do you think about this solution? Do you see some disadvantages?

I'll try that on my app and leave the feedback in here. I guess there are a lot of third party tools which only handles the "normal" page reloads and are therefore not compatible with turbolinks, so a generic solution could be useful.

Thanks for feedback.
