### ISSUE TITLE
Persist scroll on some elements.

### ISSUE THREAD

**Issue by al6x** [turbolinks/turbolinks-classic#205]
Sometimes it's desirable to persist scroll position on some elements. It's already possible to do that, but would be nice to have it out of the box.

Code below allow to preserve scroll position of `.left-content` element on page update. Would be nice to have something like `Turbolinks.persistScrollOn '.left-content'`.

``` CoffeeScript
# Persist scroll position on page updates.
elementsWithPersistentScrolls = ['.left-content']

# Storing scroll positions of scrollable elements.
persistentScrollsPositions = {}
$(document).on 'page:receive', ->
  persistentScrollsPositions = {}
  for selector in elementsWithPersistentScrolls
    persistentScrollsPositions[selector] = $(selector).scrollTop() 

$(document).on 'page:change', ->
  for selector, scrollTop of persistentScrollsPositions
    $(selector).scrollTop scrollTop 
```

**Comment by vedant1811** [comment]
thanks @alexeypetrushin for this wonderful solution
