### ISSUE TITLE
how to trigger " window.onbeforeunload " event under turbolinks ?

### ISSUE THREAD

**Issue by iamroody** [turbolinks/turbolinks-classic#249]
Many sites have such kind of functions: When user do some changes, and when he try to switch/reload/close page, site will give a notice that "unsaved changes,....". The common way is add "window.onbeforeunload" event, and return "message" to solve this problem.

but under turbolinks, page navigation could not trigger this, unless you add "data-no-turbolink" for the target links. So I check turbolinks to find another event, "page:fetch" will be triggered when page navigates, but there is no way to block browser keep on loading page.

so, Is there a good way for this ? or we could have some events like "page:pre-fetch" ?

**Comment by WojtekKruszewski** [comment]
I'm using the callback to call original onbeforeunload event handler:

```
$(document).on("page:before-change", TraceKit.wrap(function(){
  if (typeof window.onbeforeunload === "function") {
    var message = window.onbeforeunload();
    if (!window.confirm(message)) {
      return false;
    }
  }
}))
```

**Comment by pwalvarado** [comment]
This works for me: http://www.railsmine.net/2013/11/javascript-alert-for-unsaved-changes-turbolinks-jquery.html

**Comment by jhubert** [comment]
@reed Any suggestions as to how this would help with the back button being pressed? In chrome is seems to just allow the back button event to happen regardless of `onbeforeunload` or `page:before-change` events.

**Comment by reed** [comment]
Browsers don't allow the popstate event to be canceled.  There's nothing we can do to get around that.

**Comment by MauricioMoraes** [comment]
@pwalvarado, thanks for the simple and effective solution: to verify if there are unsaved changes when the user clicks a link, without the need to disable turbolinks.
Along with ```window.onbeforeunload``` this solved the issue (in my specific case).

**Comment by ginolon** [comment]
How to use it just on the pages with a form?

**Comment by junaidatique** [comment]
+1 @johnmpotter

**Comment by melnikaite** [comment]
There is a nice jquery plugin AreYouSure
I just added turbolinks support, but it's not yet merged
https://github.com/codedance/jquery.AreYouSure/pull/119

**Comment by soundasleep** [comment]
Note if you are using Turbolinks 5, the `page:before-change` event no longer exists, but you can use the `turbolinks:before-visit` event instead.

```javascript
  $(window).bind("beforeunload", function(event) {
    if (true) {
      event.returnValue = "Are you sure?";
      return event.returnValue;
    }
  });

  // Turbolinks 4 and 5
  $(document).on("page:before-change turbolinks:before-visit", function() {
    if (true) {
      return confirm("Are you sure?");
    }
  });
```
