### ISSUE TITLE
Duplicating HTML class attribute content

### ISSUE THREAD

**Issue by mbajur** [turbolinks/turbolinks-classic#270]
Hello!
I just want to report a strange behaviour of my rails app using turbolinks. My HTML tag class content is beeing duplicated each time i click a GET link. It's nothing horrible but i think it's worth reporting. 

![zrzut ekranu 2013-08-20 o 12 32 59](https://f.cloud.github.com/assets/581569/992660/f13f3212-0983-11e3-934f-98d517ef9e04.png)

**Comment by th3m4ri0** [comment]
I have the same issue but the script tag is already in the `<head>`
```
<script src="/assets/modernizr-1c4f6f2383346e76a4305023c45e4904.js"></script>
</head>
```
