### ISSUE TITLE
Turbolinks prevents WebClientView callbacks from being fired in Android 4.4 (Kit Kat)

### ISSUE THREAD

**Issue by tomafro** [turbolinks/turbolinks-classic#301]
Using turbolinks affects WebView callbacks on Android 4.4 (but not apparently 4.3 and earlier).  When clicking a link in a WebView on Android, a number of callbacks should be called. 

```
shouldOverrideUrlLoading
onPageStarted
onPageFinished
```

Assuming the request isn't overridden, these should be called in order with the `WebView` and the url of the clicked link.  This works great on Android 4.3.

In Android 4.4 however, the following callbacks are fired

```
onPageFinished (called with the original page url)
onPageFinished (called with the link url)
```

This is a real problem, as the `shouldOverrideUrlLoading` is a common way to launch native code from a WebView.

I'm actively investigating this, and will update as I find more information.

**Comment by nonameolsson** [comment]
Any news about this? Or is there a workaround? We must use turbolinks in our application, but it would be really good to be able to use it in a WebView in Android.

**Comment by marcferna** [comment]
Having a similar issue but with the iOS WKWebView. I don't really want to disable turbolinks...

**Comment by tomafro** [comment]
@jayohms Do you know anything about the latest state of this? Are we using turbolinks on later versions of our Android app?
