### ISSUE TITLE
Script tags inside body are executed multiple times

### ISSUE THREAD

**Issue by wael34218** [turbolinks/turbolinks-classic#313]
I have script tags that used to be in the head section which was executed on page load of specific pages. These scripts should be executed once and on their specific page only. When I tried Turbolinks, these scripts were not executed at all unless they exist in the initial page (the first page loaded from the server). So I moved the scripts to the end of the body section of my HTML page. Here are my findings:

1- Normal script tags:
This resulted in executing the code multiple times. So if I load the page once it will execute correctly, if I navigate away from the page and then come back to it, the code will execute twice. If I do that again then it will execute 3 times ... etc. The code is being executed from sources that starts with VM and ends with 5 digits, example VM29823 that are created in chrome each time it visits a page with script tag inside of its body. These scripts are executed even if you are navigating to a different page, for example if I visit page A with script SA then SA will be executed onload of other pages B and C. Which is, of course, not desirable.

2- script tags with data-turbolinks-eval=false:
In that case the script is only executed only if that script was called from the initial page (The first load of the website), which is a similar behaviour of adding the script to the head section instead of the body.

I need to execute my scripts only once and to their corresponding pages.

**Comment by gaganmurghai** [comment]
@wael34218 @wael34218 @reed @reed @jonnymacs @michaeltrilford 
I am using angular 4 and adding a javscript (index.js) file in my html file on specific component. But when I trying to use that javascript's file function again and again from one component to another component, its calling multiple times. As I debug I can see "VM40 index.js" with my code. I think is the issue that my function is calling multiple time. If you guys have any solution then please let me know.
