### ISSUE TITLE
Turbolinks disabled for POST requests that redirected via GET

### ISSUE THREAD

**Issue by amisarca** [turbolinks/turbolinks-classic#352]
I am using a new Rails 4.0.2 application, and the turbolinks gem.

When I create/update a RESTful resource, Turbolinks are disabled even if the resource was successfully created. For any other GET requests, Turbolinks work just fine.

This is my controller code:  

``` ruby
def create
  @comment = Comment.new(comment_params)

  if @comment.save
    redirect_to @comment, notice: 'Comment was successfully created.'
  else
    render action: 'new'
  end
end
```

Instead of redirecting to the comment via turbolinks, it does a full loading of the page.

**Comment by MauricioMoraes** [comment]
Take a look at this gem: [Turboboost](https://github.com/waymondo/turboboost)
