### ISSUE TITLE
Update the attributes of the HTML tag

### ISSUE THREAD

**Issue by IvanUkhov** [turbolinks/turbolinks-classic#375]
I have an application that supports two languages, and each page has a link that switches the current locale. In the application layout, the _lang_ attribute of the _html_ tag is being set accordingly. The content of each page extensively makes use of hyphenation, which primarily relies on the value of that attribute. Turbolinks do not seem to be updating the attributes of the _html_ tag, and hyphenation breaks down when changing the current locale.

Regards,
Ivan

**Comment by collimarco** [comment]
Same issue here with I18n. I think that turbolinks should automatically update lang attribute on html tag because it's something standard and relevant. Why not update it as we do with title?

> *Always* use a language attribute on the html tag to declare the default language of the text in the page. 
http://www.w3.org/International/questions/qa-html-language-declarations
