### ISSUE TITLE
Pre-`page:change` event when loading from cache?

### ISSUE THREAD

**Issue by rmosolgo** [turbolinks/turbolinks-classic#401]
I'm using Turbolinks with React.js and it works like charm! The page change events are really nice for cleanly mounting and unmounting React components. So far, it's like this: 
- `page:receive`: Unmount any existing components
- `page:change`: Mount components for the new page 

However, when a page is loaded from cache, there is (rightly) no `page:receive` event. In fact, there's no event at all until `page:change`. By then, it's too late to unmount components because their nodes are out of the DOM. 

Is there a pre-`page:change` event that I have overlooked? Would that be a reasonable feature for turbolinks?

**Comment by tirdadc** [comment]
@rmosolgo, do you have to write custom code to properly mount/unmount your components? I'm using Turbolinks 2.5.3 with the latest version of react-rails, and I noticed that some components do not get mounted properly when they are fetched from cache.

**Comment by rmosolgo** [comment]
Are you using react-rails `1.0.0-pre`? 

I'm using that version, plus disabling the turbolinks cache:

```js
Turbolinks.pagesCached(0)
```

**Comment by tirdadc** [comment]
Figured it out, I had two conflicting declarations that resulted in the correct binding being overridden (ie one binding was from a React component and one was a generic one for dropdowns).

I didn't need to unmount anything manually, and I still have turbolinks caching enabled and it works fine!
