### ISSUE TITLE
Turbolinks reloading page when clicking hash links

### ISSUE THREAD

**Issue by tim3z** [turbolinks/turbolinks-classic#407]
Lets say I have an anchor tag with href='#' triggering some js action. When I'm on http://somepage/ this works fine, but if I'm on http://somepage/# turbolinks will reload the page (breaking my js action).  See also http://stackoverflow.com/questions/20510358/turbolinks-causes-a-link-with-href-to-trigger-page-refresh

This can also happen with hash links. Lets say I have a page with some divs with ids 'id1' and 'id2' and I wanna have some jquery smooth scrolling between them. When I'm on http://somepage/ and I click an href='#id1' all works fine, if I then click href='id2' (and id1 again) still everything fine but as soon as I click id1 or id2 twice without the other inbetween then all following clicks will trigger turbolinks to reload the page - with the correct hash link but it will break the smooth scrolling.

This of course can be easily fixed by disabling turbolinks for these links. But nevertheless this Behaviour is quite surprising and I'm not sure if it's ment to be that way.

**Comment by abaldwin88** [comment]
Requesting this to be reopened.  I am seeing this behavior on a recent version of Microsoft Edge.  Build # 40.15063.0.0

No issues for chrome or IE11 on the same page.
