### ISSUE TITLE
DOM broken when navigating in Safari 7.1

### ISSUE THREAD

**Issue by meleyal** [turbolinks/turbolinks-classic#408]
Since Safari 7.1 I'm seeing a strange bug when moving between 2 pages.

**Without Turbolinks:**

![selection3](https://cloud.githubusercontent.com/assets/15045/4370698/8ed9056c-430c-11e4-8bf5-e2a167cbda6b.gif)

**With Turbolinks:**

![selection5](https://cloud.githubusercontent.com/assets/15045/4370721/d8259b90-430c-11e4-89a3-bd0157897320.gif)

You can see the list element becomes nested inside the form element. Inspecting the DOM confirms this:

**Before:**

![screen shot 2014-09-23 at 12 18 41](https://cloud.githubusercontent.com/assets/15045/4370584/1d613b08-430b-11e4-81db-a612becb3557.png)

**After:**

![screen shot 2014-09-23 at 12 18 58](https://cloud.githubusercontent.com/assets/15045/4370597/3e8cb050-430b-11e4-8fc2-c355fb0b39f4.png)

I've pared it down to just these 2 elements, checked closing tags, and removed all JS and CSS from the page. I also tried setting `Turbolinks.pagesCached(0)`.

This occurs and persists when navigating between pages. Refreshing the page resets it to the correct state.

**Comment by scottwb** [comment]
FWIW I have a small javascript repro that illustrates this Safari bug (still in Safari 8.0.3), very similar to @reed's console examples above, without using turbolinks/rails:

http://jsfiddle.net/spa9LbLr/2/

This shows a bare-bones document with a `<form>` and a `<div>` after it. When that HTML is parsed with `DOMParser`, you can see that it clearly pulls anything after the form up into the form. Experimenting with that jsfiddle shows that it will grab everything after the form until the closing tag of the form's parent.

Chrome, Firefox, and IE10 (didn't test lower) all parse this correctly. Wish I would have discovered this thread first, before I did all that debugging. :-$
