### ISSUE TITLE
Webpage without title, after turbolink has title of undefined

### ISSUE THREAD

**Issue by ipepe** [turbolinks/turbolinks-classic#662]
On my rails app I didn't create a title tag inside application layout, because of that, every time i go by turbolink, webpage title changes from ```http://localhost:3000/...``` to ```untitled```

**Comment by reed** [comment]
Title tags are a required element of all HTML documents.  Therefore, Turbolinks shouldn't have to handle the case where the title tag is absent.  You should just add a title so the document is valid HTML.
