### ISSUE TITLE
jQuery UI tips and tricks

### ISSUE THREAD

**Issue by davydotcom** [turbolinks/turbolinks-classic#76]
Just leaving some notes for some things i noticed when using jQuery ui components (particularly the datepicker)..

When a page has changed, the .datepicker has not reinitialized because it doesnt check to see if its datePicker div has been removed from the dom, but it has.

To correct this you can do something like this...

```
jQuery.datepicker.dpDiv.appendTo( jQuery('body') );
```

I updated this solution per @rpflorence ... thanks for the catch.

**Comment by gudata** [comment]
This solution doesn't work if one wants to use another jQueryUI component, like autocomplete.
