### ISSUE TITLE
Post request instead of get when hitting refresh

### ISSUE THREAD

**Issue by MatthieuBarthel** [turbolinks/turbolinks-classic#79]
After making a post action which don't redirects you (error messages i.e), if you navigate to any link and then hit refresh, the browser (Chrome at least) tries to refresh the current url with a post request.

Thanks for all the awesome stuff you are sharing <3
Matt

**Comment by coreyward** [comment]
Seems like this a problem again in Rails 5, at least on a non-AR model form. Anybody experiencing the same?
