### ISSUE TITLE
Possibility to replace meta tags

### ISSUE THREAD

**Issue by fred** [turbolinks/turbolinks-classic#81]
Hi, 

Currently turbolinks replaces only body and title as far as I know.

I needed to also replace other meta tags such as opengraph and HTML5 microdata.

```
<meta property="og:title" content="Article title"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="http://news.com/items/1228"/>
<meta property="og:site_name" content="News Agency"/>
<meta property="og:description" content="news"/>
<meta property="article:tag" content="Science"/>
<meta property="og:image" content="https://url.to/thumb.jpg"/>
```

What would be the best approach? maybe use javascript?

**Comment by ncri** [comment]
Adding the meta tags above including Turbolinks does not work for me. The tags don't update....

**Comment by quindici** [comment]
@dhh. You are right that when scraper discover a page it would fire a full page load request. However lots of sharing service does extract the meta tag and pass the card related information to social media directly. When Facebook get this urls for the first time, it would just cached what's given so the scraper does not work. Something flexibility to allow meta tags to be updated is very much needed.
