### ISSUE TITLE
Integration with fancyBox (v1.3.4)

### ISSUE THREAD

**Issue by ghost** [turbolinks/turbolinks-classic#96]
Hi,

I'm having issues with fancyBox integration.

When I reload gallery page everything works as expected.

When I go to gallery page using turbolink the image preview modal is not working.

I'm not getting any js errors.

Here is my application.js

``` javascript
document.addEventListener("page:load", function(){
  init('load');
});

document.addEventListener("page:change", function(){
  init('change');
});

$(document).ready(function() {
  init('ready');
});

function init(msg) {
  $("a.fancybox").fancybox();
  alert(msg);
}
```

Thanks in advance,
Marek

**Comment by sheharyarn** [comment]
The solutions mentioned by @iceless58 and @antpaw not working for me. 

Using [`Fancybox2-Rails`](https://github.com/kyparn/fancybox2-rails) (Fancybox `2.1.5`) with `Ruby 2.2.0`, `Rails 4.2.0` and `Turbolinks 2.5.3`. (cc: @kyparn)

**Comment by bbnnt** [comment]
This won"t work when using it programatically with $.fancybox.open
